version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Add your environment variables here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COPILOT_API_KEY=${COPILOT_API_KEY}
    volumes:
      # Mount data directory to persist CSV files
      - ./data:/app/data
      # Mount for development (optional - remove for production)
      - ./backend:/app:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local

networks:
  default:
    driver: bridge
